esjZone:
  # your credentials
  ews_key: ""
  ews_token: ""
  # your esjzone novel root path
  esj_root_path: "./"
  # esjzone novel urls for download
  esj_novel_url:
#    - "https://www.esjzone.me/detail/114514.html"


