toc_prefix: "<?xml version=\"1.0\" encoding=\"utf-8\"?><!DOCTYPE ncx PUBLIC \"-//NISO//DTD ncx 2005-1//EN\" \"http://www.daisy.org/z3986/2005/ncx-2005-1.dtd\">"
toc_verison: "2005-1"
toc_xmlns: "http://www.daisy.org/z3986/2005/ncx/"
toc_meta_content: "urn:uuid:5208e6bb-5d25-45b0-a7fd-b97d79a85fd4"
toc_meta_name: "dtb:uid"
episode_prefix: "<?xml version=\"1.0\" encoding=\"utf-8\"?><!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.1//EN\" \"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd\"><html xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:xml=\"http://www.w3.org/XML/1998/namespace\" xml:lang=\"zh-CN\">"